set global local_infile = 0;
SET GLOBAL secure_file_priv = "/tmp/";
show variables like "secure_file_priv";
show variables like "local_infile";

LOAD DATA  INFILE 'Pacientes.csv'
INTO TABLE PACIENTE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA  INFILE 'Habitaciones.csv'
INTO TABLE HABITACION
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA  INFILE 'LogHabitaciones.csv'
INTO TABLE TEMP_LOG_HABITACION
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA  INFILE 'Logactividades1.csv'
INTO TABLE TEMP_LOG_ACTIVIDAD
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA  INFILE 'Logactividades2.csv'
INTO TABLE TEMP_LOG_ACTIVIDAD2
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


INSERT INTO LOG_HABITACION (timestampx,statusx,idHabitacion)  select timestampx,statusx,idHabitacion from TEMP_LOG_HABITACION;

INSERT INTO LOG_ACTIVIDAD (timestampx,actividad,PACIENTE_idPaciente,HABITACION_idHabitacion)  select timestampx,actividad,idPaciente,idHabitacion from TEMP_LOG_ACTIVIDAD;
INSERT INTO LOG_ACTIVIDAD (timestampx,actividad,PACIENTE_idPaciente,HABITACION_idHabitacion)  select timestampx,actividad,idPaciente,idHabitacion from TEMP_LOG_ACTIVIDAD2;

SELECT * FROM PACIENTE LIMIT 20;
SELECT * FROM HABITACION LIMIT 20;
SELECT * FROM LOG_HABITACION LIMIT 20;
SELECT * FROM LOG_ACTIVIDAD LIMIT 20;

SELECT * FROM PACIENTE ORDER BY idPaciente DESC LIMIT 20;
SELECT * FROM HABITACION ORDER BY idHabitacion DESC LIMIT 20;
SELECT * FROM LOG_HABITACION ORDER BY idLogHabitacion DESC LIMIT 20;
SELECT * FROM LOG_ACTIVIDAD ORDER BY id_log_actividad DESC LIMIT 20;

	SELECT count(*) FROM PACIENTE;
	SELECT count(*) FROM HABITACION;
	SELECT count(*) FROM LOG_HABITACION;
	SELECT count(*) FROM LOG_ACTIVIDAD;

flush logs;